package pl.b2bnet.api.enumerate;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TagNames {
        ROCK,ELECTRONIC,SEENLIVE,ALTERNATIVE,INDIE,POP,FEMALEVOCALISTS,METAL,ALTERNATIVEROCK,JAZZ,
        CLASSICROCK,AMBIENT,EXPERIMENTAL,FOLK,PUNK,INDIEROCK,HARDROCK
        ,HIPHOP,INSTRUMENTAL,SINGERSONGWRITER,BLACKMETAL,DANCE,PROGRESSIVEROCK
        ,DEATHMETAL,HEAVYMETAL,HARDCORE,BRITISH,SOUL,CHILLOUT,ELECTRONICA,CLASSICAL,INDUSTRIAL,
        SOUNDTRACK,RAP,BLUES,PUNKROCK,THRASHMETAL,ACOUSTIC,METALCORE,PSYCHEDELIC,JAPANESE
        ,POSTROCK,PROGRESSIVEMETAL,GERMAN,FUNK,NEWWAVE,TRANCE
}
